# Generated by Django 3.1.1 on 2020-09-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='QuestionID',
            field=models.IntegerField(default=0),
        ),
    ]
