# Generated by Django 3.1.1 on 2020-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_answer_questionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='QuestionID',
            field=models.IntegerField(),
        ),
    ]
